[versions]
aboutlibraries = "11.2.3"
android_gradle_plugin = "8.6.0"
appcompat = "1.7.0"
constraint_layout = "2.1.4"
coil = "2.7.0"
core_ktx = "1.13.1"
coroutines = "1.8.1"
countly = "24.7.2"
dagger = "2.52"
datetime = "0.6.1"
espresso = "3.6.1"
datastore = "1.1.1"
flexbox = "3.0.0"
fragment = "1.8.2"
hilt_navigation = "1.2.0"
jackson = "2.17.2"
jakarta_xml = "4.0.2"
jsoup = "1.18.1"
junit = "4.13.2"
kotlin = "2.0.20"
ktfmt = "0.20.1"
lifecycle = "2.8.4"
material_3 = "1.12.0"
moshi = "1.15.1"
navigation = "2.7.7"
okhttp = "4.12.0"
paging = "3.3.2"
protobuf = "4.28.0"
protobuf_plugin = "0.9.4"
preference = "1.2.1"
recyclerview = "1.3.2"
recyclerview_selection = "1.1.0"
retrofit = "2.11.0"
room = "2.6.1"
statemachine = "0.2.0"
stax = "1.0-2"
swiperefresh = "1.1.0"
test = "1.6.1"
test_junit = "1.2.1"
timber = "5.0.1"
viewpager2 = "1.1.0"
woodstox = "7.0.0"
work = "2.9.0"

[libraries]
protobuf_core = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
protobuf_javaLite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
about_core = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
about_ui = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutlibraries" }
android_appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
android_constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint_layout" }
core_ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core_ktx" }
coroutines_core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines_android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
countly = { group = "ly.count.android", name = "sdk", version.ref = "countly" }
hilt_android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt_compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
hilt_plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "dagger" }
hilt_navigation = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "hilt_navigation" }
fragment_ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
datastore_prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore_core = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
test_espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
jackson_kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson_xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jakarta_xmlapi = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jakarta_xml" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin_stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin_plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin_reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin_datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
lifecycle_service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
lifecycle_java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle_savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle_viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
material_version3 = { group = "com.google.android.material", name = "material", version.ref = "material_3" }
moshi_runtime = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi_kapt = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
navigation_runtime = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation" }
navigation_fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation_ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
navigation_plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }
okhttp3_runtime = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp3_doh = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "okhttp" }
okhttp3_logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
paging_runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
preference_ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
recyclerview_core = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
recyclerview_selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "recyclerview_selection" }
retrofit_runtime = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit_moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit_scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
stax = { group = "javax.xml.stream", name = "stax-api", version.ref = "stax" }
statemachine = { group = "com.tinder.statemachine", name = "statemachine", version.ref = "statemachine" }
test_runner = { group = "androidx.test", name = "runner", version.ref = "test" }
test_rules = { group = "androidx.test", name = "rules", version.ref = "test" }
test_core = { group = "androidx.test", name = "core-ktx", version.ref = "test" }
test_junit = { group = "androidx.test.ext", name = "junit", version.ref = "test_junit" }
swiperefresh_layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefresh" }
test_truth = { group = "androidx.test.ext", name = "truth", version.ref = "test" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
woodstox = { group = "com.fasterxml.woodstox", name = "woodstox-core", version.ref = "woodstox" }
android_work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

[plugins]
android_application = { id = "com.android.application", version.ref = "android_gradle_plugin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf_plugin" }
