name: Build
on:
  # Trigger on every pull request and on push
  # to the `master` branch.
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
  # github does not appreciate ~ as home indicator. Prefer the full path.
    working-directory: /home/runner/work/unchained-android/unchained-android/app
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew lint test
      - name: Save test reports
        uses: actions/upload-artifact@v2
        # artifacts are zipped together in the end
        with:
            name: test-report
            path: /home/runner/work/unchained-android/unchained-android/app/app/build/reports/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve keystore for apk signing
        env:
            ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$ENCODED_KEYSTORE" | base64 --decode > /home/runner/work/unchained-android/unchained-android/app/release.pfk
      - name: Copy plugins
        run: cp /home/runner/work/unchained-android/unchained-android/extra_assets/plugins/*.unchained /home/runner/work/unchained-android/unchained-android/app/app/src/main/assets/
      - name: Check plugins folder
        run: ls /home/runner/work/unchained-android/unchained-android/extra_assets/plugins/
      - name: Check assets folder
        run: ls /home/runner/work/unchained-android/unchained-android/app/app/src/main/assets/
      - name: Build the app
        env:
            KEYSTORE: /home/runner/work/unchained-android/unchained-android/app/release.pfk
            KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew clean assembleRelease --stacktrace
      - name: Save apk
        uses: actions/upload-artifact@v2
        with:
            name: apk
            path: /home/runner/work/unchained-android/unchained-android/app/app/build/outputs/apk/release/*.apk

