name: Build
on:
  # Trigger on every pull request and on push
  # to the `master` branch.
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
  # github does not appreciate ~ as home indicator. Prefer the full path.
    working-directory: /home/runner/work/unchained-android/unchained-android/app
jobs:
  lint-release:
    name: Run Release Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: ./gradlew ktfmtCheck
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Retrieve keystore for apk signing
        env:
            ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$ENCODED_KEYSTORE" | base64 --decode > /home/runner/work/unchained-android/unchained-android/app/release.pfk
      - name: Build the app
        env:
            KEYSTORE: /home/runner/work/unchained-android/unchained-android/app/release.pfk
            KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew clean assembleRelease --stacktrace
      - name: Save apk
        uses: actions/upload-artifact@v4
        with:
            name: apk
            path: /home/runner/work/unchained-android/unchained-android/app/app/build/outputs/apk/release/*.apk
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Retrieve keystore for apk signing
        env:
            ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
        run: echo "$ENCODED_KEYSTORE" | base64 --decode > /home/runner/work/unchained-android/unchained-android/app/release.pfk
      - name: Build the app
        env:
            KEYSTORE: /home/runner/work/unchained-android/unchained-android/app/release.pfk
            KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew clean assembleDebug --stacktrace
      - name: Save apk
        uses: actions/upload-artifact@v4
        with:
            name: apk-debug
            path: /home/runner/work/unchained-android/unchained-android/app/app/build/outputs/apk/debug/*.apk

